alg: random_search
base_dir: log/random_search/hanoi/
log_level: INFO
gpu: 0
data:
  batch_size: 200
  test_batch_size: 1
  dataset: data/npz/random_search.npz
  test_size: 0.2
  valid_size: 0.2
model:
  type: lstm_ed
  seq_len: 48
  horizon: 1
  input_dim: 4
  l1_decay: 0
  output_dim: 1
  rnn_units: 100
  rnn_layers: 1
  verified_percentage: 1
train:
  dropout: 0
  epochs: 300
  optimizer: adam
  patience: 15